version: "3.8"

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS_ROOT}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - mysql-datavolume:/var/lib/mysql
    container_name: cnc-admin-mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    volumes:
      - /sessions
    container_name: cnc-admin-phpmyadmin

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    container_name: cnc-admin-redis

volumes:
  mysql-datavolume:
