name: cnc-local-app
channels:
  - defaults
  - conda-forge
dependencies:
  - alembic
  - bcrypt
  - pip
  - psycopg2
  - pyqt
  - pyserial
  - python-dotenv
  - sqlalchemy
  - pip:
    - "celery[redis]"
